apiVersion : apps/v1
kind: Deployment
metadata:
  name: app1nginxaks 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app1nginxaks
  template:
    metadata:
      labels:
        app: app1nginxaks 
    spec:
      tolerations: 
        - key: "CriticalAddonsOnly"
          operator: "Equal"
          value: "true"
          effect: "NoSchedule"
      containers:
        - name: app1nginxaks 
          image: kontainer.azurecr.io/app1nginxaks
          ports:
          - containerPort: 80
